version: "3"

services:
  ocaml:
    build:
      context: .
      dockerfile: ./OCaml/Dockerfile
    volumes:
      - ".:/app"
    command:
      bash -c "cd ./OCaml && dune exec utir ../${OUTPUT} ../sample_data/test_string.ml"
    # tty: true # 起動状態を維持する
