version: "3"

services:
  python:
    build:
      context: .
      dockerfile: "./python/Dockerfile"
    volumes:
      - ".:/app"
    command:
      bash -c "cd ./python && python main.py ../${PYTHON_SOURCE} ../${IR_DIST}"
  ocaml:
    build:
      context: .
      dockerfile: ./OCaml/Dockerfile
    volumes:
      - ".:/app"
    command:
      bash -c "cd ./OCaml && dune exec utir -- -i ../${IR_DIST} -o ../${OCAML_DIST}"
    # tty: true # 起動状態を維持する
  kotlin:
    build:
      context: .
      dockerfile: "./kotlin/Dockerfile"
    volumes:
      - ".:/app"
    command:
      bash -c "cd ./kotlin && gradle run --args='-i ../${IR_DIST} -o ../${KOTLIN_DIST}'"
  swift:
    build:
      context: .
      dockerfile: "./swift/Dockerfile"
    volumes:
      - ".:/app"
    command:
      bash -c " cd ./swift && swift run utir-swift -i ../${IR_DIST} -o ../${SWIFT_DIST}"
